### ISSUE TITLE
Error when opening on windows

### ISSUE THREAD

**Issue by osum4est** [Open-RIO/ButterKnife#1]
Here's the output from running the *.exe on windows.

````
C:\Users\osumf\Downloads\ButterKnife>butterknife.exe
 ________    ______                 __
((       )  /_  __/___  ____ ______/ /_
||  o o  |   / / / __ \/ __ `/ ___/ __/
||   3   |  / / / /_/ / /_/ (__  ) /_
\\_______/ /_/  \____/\__,_/____/\__/
                Toast ButterKnife CLI

C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/lib/ruby/2.2.0/rubygems/core_ext/k
ernel_require.rb:54:in `require': 126: The specified module could not be found.
  - C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/lib/ruby/2.2.0/x64-mingw32/ope
nssl.so (LoadError)
        from C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/lib/ruby/2.2.0/rubyge
ms/core_ext/kernel_require.rb:54:in `require'
        from C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/lib/ruby/2.2.0/openss
l.rb:17:in `<top (required)>'
        from C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/lib/ruby/2.2.0/rubyge
ms/core_ext/kernel_require.rb:54:in `require'
        from C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/lib/ruby/2.2.0/rubyge
ms/core_ext/kernel_require.rb:54:in `require'
        from C:/Users/osumf/Downloads/ButterKnife/bnlib/ruby/fetch/toast.rb:2:in
 `<top (required)>'
        from C:/Users/osumf/Downloads/ButterKnife/bnlib/ruby/cli.rb:44:in `requi
re_relative'
        from C:/Users/osumf/Downloads/ButterKnife/bnlib/ruby/cli.rb:44:in `<clas
s:CLI>'
        from C:/Users/osumf/Downloads/ButterKnife/bnlib/ruby/cli.rb:21:in `<modu
le:Butterknife>'
        from C:/Users/osumf/Downloads/ButterKnife/bnlib/ruby/cli.rb:8:in `<top (
required)>'
        from C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/lib/ruby/2.2.0/rubyge
ms/core_ext/kernel_require.rb:54:in `require'
        from C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/lib/ruby/2.2.0/rubyge
ms/core_ext/kernel_require.rb:54:in `require'
        from C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/src/butterknife:22:in
 `<module:Butterknife>'
        from C:/Users/osumf/AppData/Local/Temp/ocr7239.tmp/src/butterknife:2:in
`<main>'
````

**Comment by JacisNonsense** [comment]
As a temporary fix, try installing Ruby on your system. I'll try and add the missing libs tonight

**Comment by osum4est** [comment]
I actually tried that -- But I got another error. I ran "ruby butterknife" and got this error: "Couldn't check for Toast Updates. You might not be connected to the internet :(\nNo local Toast Files found... Installer cannot continue."

**Comment by JacisNonsense** [comment]
Patch coming tonight to fix that

**Comment by JacisNonsense** [comment]
The latest commits fixes the "Couldn't check for Toast Updates." error. You can clone the git repo and run ``` ruby butterknife ``` to deploy now. I'll work more on the Windows executable build later in the week.

**Comment by osum4est** [comment]
Unfortunately, I'm getting a new error when running via ruby....

````
C:\Users\osumf\Downloads\ButterKnife-master\ButterKnife-master>ruby butterknife
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require':
C:/Users/osumf/Downloads/ButterKnife-master/ButterKnife-master/bnlib/ruby/cli.rb
:10: syntax error, unexpected ':', expecting tASSOC (SyntaxError)
    "USB Tether Deployment": "usb_t.rb",
                            ^
C:/Users/osumf/Downloads/ButterKnife-master/ButterKnife-master/bnlib/ruby/cli.rb
:10: syntax error, unexpected ',', expecting keyword_end
C:/Users/osumf/Downloads/ButterKnife-master/ButterKnife-master/bnlib/ruby/cli.rb
:11: syntax error, unexpected ':', expecting keyword_end
    "USB Drive Deployment": "usb.rb",
                           ^
C:/Users/osumf/Downloads/ButterKnife-master/ButterKnife-master/bnlib/ruby/cli.rb
:11: syntax error, unexpected ',', expecting keyword_end
C:/Users/osumf/Downloads/ButterKnife-master/ButterKnife-master/bnlib/ruby/cli.rb
:12: syntax error, unexpected ':', expecting keyword_end
    "Network Deployment": "network.rb"
                         ^
C:/Users/osumf/Downloads/ButterKnife-master/ButterKnife-master/bnlib/ruby/cli.rb
:13: syntax error, unexpected '}', expecting keyword_end
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:i
n `require'
        from butterknife:22:in `<module:Butterknife>'
        from butterknife:2:in `<main>'
````

**Comment by osum4est** [comment]
Nevermind, i updated ruby to v2 and it works now :)

**Comment by JacisNonsense** [comment]
The windows executable should work without Ruby installed now. Sorry about the delay
